// <auto-generated />
using AssignmentMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignmentMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220831120417_initseedtables")]
    partial class initseedtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssignmentMVC.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCity");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            IdCity = 1,
                            CityName = "Borås"
                        },
                        new
                        {
                            IdCity = 2,
                            CityName = "Gothenburg"
                        },
                        new
                        {
                            IdCity = 3,
                            CityName = "Stockholm"
                        },
                        new
                        {
                            IdCity = 4,
                            CityName = "Moscow"
                        },
                        new
                        {
                            IdCity = 5,
                            CityName = "Novosibirsk"
                        },
                        new
                        {
                            IdCity = 6,
                            CityName = "WashingtonDC"
                        },
                        new
                        {
                            IdCity = 7,
                            CityName = "New York"
                        },
                        new
                        {
                            IdCity = 8,
                            CityName = "Chicago"
                        },
                        new
                        {
                            IdCity = 9,
                            CityName = "Buenos Aires"
                        },
                        new
                        {
                            IdCity = 10,
                            CityName = "Lanus"
                        },
                        new
                        {
                            IdCity = 11,
                            CityName = "Rosario"
                        });
                });

            modelBuilder.Entity("AssignmentMVC.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCountry"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCountry");

                    b.ToTable("Contries");

                    b.HasData(
                        new
                        {
                            IdCountry = 1,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            IdCountry = 2,
                            CountryName = "Russia"
                        },
                        new
                        {
                            IdCountry = 3,
                            CountryName = "USA"
                        },
                        new
                        {
                            IdCountry = 4,
                            CountryName = "Argentina"
                        });
                });

            modelBuilder.Entity("AssignmentMVC.Models.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            City = "Borås",
                            FullName = "Daniel Oikarainen",
                            PhoneNumber = "033-0000000"
                        },
                        new
                        {
                            IdPerson = 2,
                            City = "Gothenburg",
                            FullName = "Marko Kiwi",
                            PhoneNumber = "031-11111"
                        },
                        new
                        {
                            IdPerson = 3,
                            City = "WashingtonDC",
                            FullName = "Donald Trumph",
                            PhoneNumber = "011-222222"
                        },
                        new
                        {
                            IdPerson = 4,
                            City = "Moscow",
                            FullName = "Vladimir Putin",
                            PhoneNumber = "007-3333333"
                        },
                        new
                        {
                            IdPerson = 5,
                            City = "Borås",
                            FullName = "Helge Skoog",
                            PhoneNumber = "033-2178328"
                        },
                        new
                        {
                            IdPerson = 6,
                            City = "Gothenburg",
                            FullName = "Leif Mannerström",
                            PhoneNumber = "031-834129"
                        },
                        new
                        {
                            IdPerson = 7,
                            City = "WashingtonDC",
                            FullName = "Ronald Reagan",
                            PhoneNumber = "011-5781245"
                        },
                        new
                        {
                            IdPerson = 8,
                            City = "Moscow",
                            FullName = "Alexander Ovechkin",
                            PhoneNumber = "007-45891212"
                        },
                        new
                        {
                            IdPerson = 9,
                            City = "Moscow",
                            FullName = "Nikolai Karpov",
                            PhoneNumber = "007-57643154"
                        },
                        new
                        {
                            IdPerson = 10,
                            City = "Novosibirsk",
                            FullName = "Aleksandr Karelin",
                            PhoneNumber = "007-98723762"
                        },
                        new
                        {
                            IdPerson = 11,
                            City = "Stockholm",
                            FullName = "Jan-Ove",
                            PhoneNumber = "08-98723762"
                        },
                        new
                        {
                            IdPerson = 12,
                            City = "Stockholm",
                            FullName = "Mats Sundin",
                            PhoneNumber = "08-91736725"
                        },
                        new
                        {
                            IdPerson = 13,
                            City = "WashingtonDC",
                            FullName = "John Edgar Hoover",
                            PhoneNumber = "011-9823929"
                        },
                        new
                        {
                            IdPerson = 14,
                            City = "WashingtonDC",
                            FullName = "Samuel Jackson",
                            PhoneNumber = "011-1247182"
                        },
                        new
                        {
                            IdPerson = 15,
                            City = "New York",
                            FullName = "Michael Jordan",
                            PhoneNumber = "011-872435634"
                        },
                        new
                        {
                            IdPerson = 16,
                            City = "New York",
                            FullName = "Al Pacino",
                            PhoneNumber = "011-354312447"
                        },
                        new
                        {
                            IdPerson = 17,
                            City = "New York",
                            FullName = "Denzel Washington",
                            PhoneNumber = "011-23451234"
                        },
                        new
                        {
                            IdPerson = 18,
                            City = "Chicago",
                            FullName = "Harrison Ford",
                            PhoneNumber = "011-999666999"
                        },
                        new
                        {
                            IdPerson = 19,
                            City = "Chicago",
                            FullName = "Hugh Hefner",
                            PhoneNumber = "011-69696969"
                        },
                        new
                        {
                            IdPerson = 20,
                            City = "Buenos Aires",
                            FullName = "Diego Simeone",
                            PhoneNumber = "0054-69696969"
                        },
                        new
                        {
                            IdPerson = 21,
                            City = "Buenos Aires",
                            FullName = "Pope Francis",
                            PhoneNumber = "0054-69696969"
                        },
                        new
                        {
                            IdPerson = 22,
                            City = "Lanus",
                            FullName = "Diego Maradona",
                            PhoneNumber = "0054-69696969"
                        },
                        new
                        {
                            IdPerson = 23,
                            City = "Rosario",
                            FullName = "Lionel Messi",
                            PhoneNumber = "0054-69696969"
                        },
                        new
                        {
                            IdPerson = 24,
                            City = "Rosario",
                            FullName = "Che Guevara",
                            PhoneNumber = "0054-69696969"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
