// <auto-generated />
using AssignmentMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignmentMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220830074856_SeedPeopleTable")]
    partial class SeedPeopleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssignmentMVC.Models.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            City = "Borås",
                            FullName = "Daniel Oikarainen",
                            PhoneNumber = "033-0000000"
                        },
                        new
                        {
                            IdPerson = 2,
                            City = "Göteborg",
                            FullName = "Marko Kiwi",
                            PhoneNumber = "031-11111"
                        },
                        new
                        {
                            IdPerson = 3,
                            City = "WashingtonDC",
                            FullName = "Donald Trumph",
                            PhoneNumber = "011-222222"
                        },
                        new
                        {
                            IdPerson = 4,
                            City = "Moskva",
                            FullName = "Vladimir Putin",
                            PhoneNumber = "007-3333333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
